"use client";

/**
 * Admin Configuration settings.
 *
 * Mirrors the fields encoded in the v2 admin QR (see
 * @/lib/config/t3rminal-config-qr) as read-only rows. Empty before the
 * merchant has ever scanned an admin QR. Tapping "Scan QR" navigates to
 * /scan-config; on a successful decode that page persists the payload via
 * `importAdminQrConfig` and bounces back here so the values populate.
 */

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, ScanLine, Trash2, ShieldCheck } from "lucide-react";

import {
  type T3rminalConfigQrPayloadV2,
} from "@/lib/config/t3rminal-config-qr";

import {
  ADMIN_QR_PAYLOAD_SETTING,
  ADMIN_QR_RAW_SETTING,
  loadAdminQrPayload,
} from "@/lib/config/admin-qr";
import { deleteSetting } from "@/lib/storage/database";
import { onStorageChange } from "@/lib/storage/host-storage";
import { BottomNav } from "@/components/bottom-nav";

export default function AdminConfigPage() {
  const [payload, setPayload] = useState<T3rminalConfigQrPayloadV2 | null>(null);
  const [loading, setLoading] = useState(true);

  const refresh = useCallback(async () => {
    setLoading(true);
    const p = await loadAdminQrPayload();
    setPayload(p);
    setLoading(false);
  }, []);

  useEffect(() => {
    refresh();
    // Host-storage "settings" table is where the QR payload lives —
    // listen for changes so a fresh scan instantly repopulates the view
    // without the merchant having to navigate away and back.
    return onStorageChange("settings", () => {
      refresh();
    });
  }, [refresh]);

  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const handleClear = async () => {
    if (
      !confirm(
        "Remove the saved admin configuration from this terminal? The item catalog will be kept until you rescan or edit it manually.",
      )
    ) {
      return;
    }
    setErrorMsg(null);
    try {
      // Sequential — both writes target the same `settings` table and
      // concurrent writes to the same host-storage key can fail with
      // `StorageErr::Unknown`.
      await deleteSetting(ADMIN_QR_PAYLOAD_SETTING);
      await deleteSetting(ADMIN_QR_RAW_SETTING);
      refresh();
    } catch (err) {
      setErrorMsg(err instanceof Error ? err.message : String(err));
    }
  };


  return (
    <div className="h-dvh bg-black text-white flex flex-col overflow-hidden">
      <div className="flex-1 min-h-0 flex flex-col max-w-md mx-auto w-full">
        <header className="flex items-center gap-3 px-5 py-4">
          <Link
            href="/settings"
            className="text-neutral-400 hover:text-white"
            aria-label="Back to Settings"
          >
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <h1 className="text-lg font-semibold">Admin Configuration</h1>
        </header>

        <main className="flex-1 min-h-0 overflow-y-auto px-5 py-6 space-y-6">
        {/* Status + scan trigger */}
        <section className="rounded-xl border border-neutral-800 bg-neutral-900/40 p-4 space-y-3">
          <div className="flex items-center gap-2 text-sm">
            <ShieldCheck
              className={`w-4 h-4 ${payload ? "text-green-400" : "text-neutral-500"}`}
            />
            <span className="font-medium">
              {payload
                ? "Terminal is configured"
                : loading
                  ? "Loading…"
                  : "Not configured"}
            </span>
          </div>
          <p className="text-xs text-neutral-400">
            Scan the QR generated by W3sPay admin to bind this terminal to a
            merchant, populate the item catalog, and install the report
            encryption password.
          </p>
          <Link
            href="/scan-config?return=/settings/admin-config"
            className="w-full flex items-center justify-center gap-2 bg-white text-black font-semibold py-3 rounded-xl"
          >
            <ScanLine className="w-4 h-4" />
            {payload ? "Rescan to update" : "Scan QR"}
          </Link>
          {errorMsg ? (
            <p className="text-xs text-red-400 break-words">{errorMsg}</p>
          ) : null}
        </section>

        {/* Fields populated from the last scan */}
        <FieldGroup title="Merchant">
          <Field label="Display name" value={payload?.displayName} />
          <Field label="Merchant ID" value={payload?.merchantId} mono />
          <Field label="Merchant key" value={payload?.merchantKey} mono />
          <Field
            label="Receiving address"
            value={payload?.receivingAddress}
            mono
          />
        </FieldGroup>

        <FieldGroup title="Terminal">
          <Field label="Terminal ID" value={payload?.terminalId} mono />
          <Field label="Issued at" value={payload?.issuedAt} />
        </FieldGroup>

        <FieldGroup title="Business profile">
          <Field label="Name" value={payload?.profile?.name} />
          <Field label="Address line 1" value={payload?.profile?.addressLine1} />
          <Field label="Address line 2" value={payload?.profile?.addressLine2} />
          <Field label="Phone" value={payload?.profile?.phone} />
          <Field label="Tax ID" value={payload?.profile?.taxId} mono />
        </FieldGroup>

        <FieldGroup title="Report password">
          <Field label="Scheme" value={payload?.passwordScheme} />
          <Field
            label="Password"
            value={payload?.reportPassword}
            mono
            mask
          />
        </FieldGroup>

        <FieldGroup title="Item config">
          <Field label="Config name" value={payload?.config.name} />
          <Field label="Config ID" value={payload?.config.id} mono />
          <Field label="Updated at" value={payload?.config.updatedAt} />
          <Field
            label="Item count"
            value={
              payload ? String(payload.config.items.length) : undefined
            }
          />
        </FieldGroup>

        {payload ? (
          <button
            type="button"
            onClick={handleClear}
            className="w-full flex items-center justify-center gap-2 border border-red-900/60 text-red-300 py-3 rounded-xl text-sm"
          >
            <Trash2 className="w-4 h-4" />
            Clear configuration
          </button>
        ) : null}
        </main>
      </div>
      <BottomNav />
    </div>
  );
}

/* ── field rows ─────────────────────────────────────────────────── */

function FieldGroup({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="space-y-2">
      <h2 className="text-xs font-semibold uppercase tracking-wide text-neutral-500">
        {title}
      </h2>
      <div className="rounded-xl border border-neutral-800 bg-neutral-900/40 divide-y divide-neutral-800">
        {children}
      </div>
    </section>
  );
}

interface FieldProps {
  label: string;
  value: string | undefined;
  mono?: boolean;
  /** Replace the value with bullets but expose original on long-press / select. */
  mask?: boolean;
}

function Field({ label, value, mono = false, mask = false }: FieldProps) {
  const display =
    value === undefined || value === null || value === ""
      ? "—"
      : mask
        ? "•".repeat(Math.min(value.length, 24))
        : value;
  return (
    <div className="px-4 py-3 flex items-start justify-between gap-3">
      <span className="text-xs text-neutral-400 shrink-0 pt-0.5">{label}</span>
      <span
        className={`text-sm text-right break-all ${
          value ? "text-neutral-100" : "text-neutral-600"
        } ${mono ? "font-mono text-xs" : ""}`}
        title={mask && value ? value : undefined}
      >
        {display}
      </span>
    </div>
  );
}
